

---
title: "Monte Carlo Simulation Using For Loops (elasticity/standarderror)"
output: html_notebook
---

This is a simulation design. 

```{r}
library(pacman)
pacman::p_load(data.table, fixest, stargazer, dplyr, magrittr) 
```

Model: 
$$
X =  \beta_1 +U
$$

```{r OLS-n-100-M-100000}

## Parameters and seed
set.seed(1)  # Seed
n = 1000     # Sample size
M = 10000   # Number of experiments/iterations

## Storage 
slope_DT <- rep(0,M)
#intercept_DT <- rep(0,M)

## Begin Monte Carlo

for (i in 1:M){ #  M is the number of iterations
  
  # Generate data
  U_i = rnorm(n, mean = 0, sd = 1) # Error
  X_i = rnorm(n, mean = 0.059, sd = 0.028) # mean and sd of water quality elasticity
  Y_i = X_i + U_i  # Dependent variable
  
  # Formulate data.table
  data_i = data.table(X = X_i, Y = Y_i)
  
  # Run regressions
  ols_i <- lm(data = data_i, Y_i ~ 1)
  
  
  # Extract slope coefficient and save
  slope_DT[i] <- ols_i$coefficients[1]
  
}


# Summary statistics
estimates_DT <- data.table(beta_1 = slope_DT)
stargazer(estimates_DT[, c("beta_1")], type = "text", digits = 5)



```
